### ISSUE TITLE
Raised OOM when training bicycle scene of m360

### ISSUE THREAD

**Issue by Falcom4000** [YouyuChen0207/DashGaussian#21]
$ python full_eval.py -m360 /hpc2hdd/home/hsong425/3dgs/data/360_v2 --output_path output/official_fast_dash --gpu 0 -
-fast --dash
Optimizing output/official_fast_dash/bicycle
Training progress:   0%|                                                                                                                  | 0/30000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/hpc2hdd/home/hsong425/3dgs/DashGaussian/train_dash.py", line 313, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, ar
gs.debug_from)
  File "/hpc2hdd/home/hsong425/3dgs/DashGaussian/train_dash.py", line 121, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp, separate_sh=SPARSE_ADAM_AVAILABLE, render_size=gt_image.shape[-2
:])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^
  File "/hpc2hdd/home/hsong425/3dgs/DashGaussian/gaussian_renderer/__init__.py", line 91, in render
    rendered_image, radii, depth_image = rasterizer(
                                         ^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/diff_gaussian_rasterization/__init__.py", line 228, in forward
    return rasterize_gaussians(
           ^^^^^^^^^^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/diff_gaussian_rasterization/__init__.py", line 33, in rasterize_gaussians
    return _RasterizeGaussians.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc2hdd/home/hsong425/.conda/envs/llm/lib/python3.12/site-packages/diff_gaussian_rasterization/__init__.py", line 98, in forward
    num_rendered, num_buckets, color, invdepths, radii, geomBuffer, binningBuffer, imgBuffer, sampleBuffer = _C.rasterize_gaussians(*args)
                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.01 GiB. GPU 0 has a total capacity of 79.33 GiB of which 75.72 GiB is free. Process 2757994 has 3.60 GiB memory in use. Of the allocated memory 3.06 GiB is allocated by PyTorch, and 16.07 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 
Training progress:   0%|                                                                                                                  | 0/30000 [00:00<?, ?it/s]

**Comment by Falcom4000** [comment]
Environment:
NVIDIA A800-SXM4-80GB
PyTorch version: 2.5.1
CUDA version: 12.1
cuDNN version: 90100

**Comment by Falcom4000** [comment]
After recompiling submodules, the problem has been solved
