### ISSUE TITLE
cuFFT error: CUFFT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by FDF521X** [YouyuChen0207/DashGaussian#4]
Thank you for your excellent work. After configuring the environment as required (cuda 11.6 + pytorch 1.12.1), I encountered the error "cuFFT error: CUFFT_INTERNAL_ERROR." How should I resolve this?

**Comment by YouyuChen0207** [comment]
I don't know what hardware platform you are using. Basically there should be no problem if your local environment can run the [vanilla 3DGS](https://github.com/graphdeco-inria/gaussian-splatting). You can follow the environment setup there to run vanilla 3DGS first, and the same environment should work for DashGaussian. If you are using a GPU greater than RTX3090, I suppose install the up-to-date torch version and compile the submodules with corresponding version of CUDA may fix the problem.

**Comment by FDF521X** [comment]
Thank you for your reply. I resolved the issue using CUDA 11.8 and PyTorch 2.0. Additionally, I noticed that DashGS does not use depth, and the part of the code handling depth does not downsample the depth map. Is this reasonable?

**Comment by YouyuChen0207** [comment]
We didn't develop DashGaussian for the scenario with depth supervision, but I think this can be updated into the codebase to make it more robust. Thanks for your advise.
